# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: ECPA.ca
    url: https://www.ecpa.ca/
    weight: 10
  - name: Archive (2005–2022)
    url: https://archive.ecpa.ca/
    weight: 20
